import {
  Calendar,
  Baby,
  Activity,
  Calculator,
  Hand,
  Timer,
  TrendingUp,
  Droplet,
  AlertTriangle,
  Heart,
  Pill,
  Brain,
  CircleDot,
  GlassWater,
  Dumbbell,
  Syringe,
  CheckSquare,
} from "lucide-react";

export const toolsData = [
  {
    id: "ovulation-calculator",
    title: "Ovulation Calculator",
    description: "Track your fertile window and predict ovulation dates based on your menstrual cycle.",
    icon: Calendar,
    category: "Fertility",
    href: "/tools/ovulation-calculator",
  },
  {
    id: "due-date-calculator",
    title: "Due Date Calculator",
    description: "Calculate your estimated due date based on your last menstrual period or conception date.",
    icon: Baby,
    category: "Pregnancy",
    href: "/tools/due-date-calculator",
  },
  {
    id: "cycle-tracker",
    title: "Cycle Tracker",
    description: "Log and track your menstrual cycles, symptoms, and patterns over time.",
    icon: Activity,
    category: "Menstrual Health",
    href: "/tools/cycle-tracker",
  },
  {
    id: "pregnancy-bmi",
    title: "Pregnancy BMI",
    description: "Calculate your BMI and recommended weight gain during pregnancy.",
    icon: Calculator,
    category: "Pregnancy",
    href: "/tools/pregnancy-bmi",
  },
  {
    id: "kick-counter",
    title: "Kick Counter",
    description: "Track your baby's movements to monitor fetal activity and wellbeing.",
    icon: Hand,
    category: "Pregnancy",
    href: "/tools/kick-counter",
  },
  {
    id: "contraction-timer",
    title: "Contraction Timer",
    description: "Time your contractions to know when it's time to head to the hospital.",
    icon: Timer,
    category: "Labor",
    href: "/tools/contraction-timer",
  },
  {
    id: "fetal-growth",
    title: "Fetal Growth Tracker",
    description: "Track your baby's growth week by week with size comparisons.",
    icon: TrendingUp,
    category: "Pregnancy",
    href: "/tools/fetal-growth",
  },
  {
    id: "blood-type",
    title: "Blood Type Calculator",
    description: "Predict possible blood types for your baby based on parents' blood types.",
    icon: Droplet,
    category: "Genetics",
    href: "/tools/blood-type",
  },
  {
    id: "gestational-diabetes",
    title: "GDM Risk Assessment",
    description: "Assess your risk factors for gestational diabetes mellitus.",
    icon: AlertTriangle,
    category: "Risk Assessment",
    href: "/tools/gestational-diabetes",
  },
  {
    id: "preeclampsia-risk",
    title: "Preeclampsia Risk",
    description: "Evaluate risk factors for preeclampsia during pregnancy.",
    icon: Heart,
    category: "Risk Assessment",
    href: "/tools/preeclampsia-risk",
  },
  {
    id: "safe-medications",
    title: "Safe Medications",
    description: "Quick reference guide for medication safety during pregnancy and breastfeeding.",
    icon: Pill,
    category: "Reference",
    href: "/tools/safe-medications",
  },
  {
    id: "ppd-screener",
    title: "PPD Screener (EPDS)",
    description: "Edinburgh Postnatal Depression Scale screening questionnaire.",
    icon: Brain,
    category: "Mental Health",
    href: "/tools/ppd-screener",
  },
  {
    id: "breastfeeding-tracker",
    title: "Breastfeeding Tracker",
    description: "Log feeding sessions, duration, and track your baby's feeding patterns.",
    icon: CircleDot,
    category: "Postpartum",
    href: "/tools/breastfeeding-tracker",
  },
  {
    id: "water-intake",
    title: "Water Intake Tracker",
    description: "Track daily hydration goals especially important during pregnancy.",
    icon: GlassWater,
    category: "Wellness",
    href: "/tools/water-intake",
  },
  {
    id: "exercise-guide",
    title: "Exercise Guide",
    description: "Safe exercise recommendations for each trimester of pregnancy.",
    icon: Dumbbell,
    category: "Wellness",
    href: "/tools/exercise-guide",
  },
  {
    id: "vaccination-schedule",
    title: "Vaccination Schedule",
    description: "Recommended vaccination timeline during pregnancy and for newborns.",
    icon: Syringe,
    category: "Reference",
    href: "/tools/vaccination-schedule",
  },
  {
    id: "hospital-bag",
    title: "Hospital Bag Checklist",
    description: "Complete checklist to prepare your hospital bag for delivery.",
    icon: CheckSquare,
    category: "Preparation",
    href: "/tools/hospital-bag",
  },
];

export const categories = [
  "All",
  "Fertility",
  "Pregnancy",
  "Labor",
  "Postpartum",
  "Risk Assessment",
  "Mental Health",
  "Wellness",
  "Reference",
  "Preparation",
  "Genetics",
  "Menstrual Health",
];
