// Generated from src/data/articles.ts — keep in sync.
// All 36 article seeds across 3 sections (planning/pregnant/postpartum).
export const ARTICLE_SEED_REGISTRY = [
  // ── PLANNING (11) ──────────────────────────────────────────────────
  { slug: "fertility-window-guide", section: "planning", type: "article", tags: ["fertility", "timing", "cycle-awareness"], titles: { ar: "نافذة الخصوبة بوضوح", en: "Understanding your fertility window", de: "Das Fruchtbarkeitsfenster verstehen", fr: "Comprendre la fenêtre de fertilité", es: "Entender la ventana fértil", tr: "Doğurganlık dönemini anlamak", pt: "Entender a janela fértil" } },
  { slug: "cycle-quality-signals", section: "planning", type: "research", tags: ["cycle-awareness", "patterns", "tracking"], titles: { ar: "إشارات جودة الدورة", en: "Cycle quality signals", de: "Signale der Zyklusqualität", fr: "Signaux de qualité du cycle", es: "Señales de calidad del ciclo", tr: "Döngü kalitesi sinyalleri", pt: "Sinais de qualidade do ciclo" } },
  { slug: "preconception-nutrition-readiness", section: "planning", type: "article", tags: ["nutrition", "readiness", "vitamins"], titles: { ar: "الاستعداد الغذائي قبل الحمل", en: "Nutrition readiness before pregnancy", de: "Ernährungsstart vor der Schwangerschaft", fr: "Préparer la nutrition avant la grossesse", es: "Preparación nutricional antes del embarazo", tr: "Hamilelik öncesi beslenme hazırlığı", pt: "Preparação nutricional antes da gravidez" } },
  { slug: "sleep-and-fertility", section: "planning", type: "research", tags: ["sleep", "fertility", "routine"], titles: { ar: "النوم ودوره في الخصوبة", en: "Sleep and fertility balance", de: "Schlaf und Fruchtbarkeit im Gleichgewicht", fr: "Sommeil et équilibre de fertilité", es: "Sueño y equilibrio de la fertilidad", tr: "Uyku ve doğurganlık dengesi", pt: "Sono e equilíbrio da fertilidade" } },
  { slug: "when-to-use-cycle-tracking", section: "planning", type: "article", tags: ["tracking", "cycle-awareness", "planning"], titles: { ar: "متى يفيد تتبع الدورة فعلاً؟", en: "When cycle tracking helps most", de: "Wann Zyklustracking am meisten hilft", fr: "Quand le suivi du cycle aide le plus", es: "Cuándo ayuda más seguir el ciclo", tr: "Döngü takibi en çok ne zaman fayda sağlar", pt: "Quando o acompanhamento do ciclo ajuda mais" } },
  { slug: "ovulation-practical-guide", section: "planning", type: "article", tags: ["ovulation", "timing", "planning"], titles: { ar: "فهم الإباضة بشكل عملي", en: "A practical guide to ovulation", de: "Ovulation praktisch verstehen", fr: "Comprendre l’ovulation de façon pratique", es: "Entender la ovulación de forma práctica", tr: "Yumurtlamayı pratik şekilde anlamak", pt: "Entender a ovulação de forma prática" } },
  { slug: "emotional-planning-before-pregnancy", section: "planning", type: "article", tags: ["mindset", "planning", "support"], titles: { ar: "الاستعداد النفسي قبل الحمل", en: "Emotional planning before pregnancy", de: "Mentale Vorbereitung vor der Schwangerschaft", fr: "Préparation émotionnelle avant la grossesse", es: "Preparación emocional antes del embarazo", tr: "Hamilelik öncesi duygusal hazırlık", pt: "Planejamento emocional antes da gravidez" } },
  { slug: "common-trying-to-conceive-mistakes", section: "planning", type: "article", tags: ["mistakes", "planning", "fertility"], titles: { ar: "أخطاء شائعة عند محاولة الحمل", en: "Common mistakes while trying to conceive", de: "Häufige Fehler beim Kinderwunsch", fr: "Erreurs fréquentes quand on essaie de concevoir", es: "Errores comunes al intentar concebir", tr: "Hamile kalmaya çalışırken yapılan yaygın hatalar", pt: "Erros comuns ao tentar engravidar" } },
  { slug: "daily-routine-discovery", section: "planning", type: "discovery", tags: ["routine", "sleep", "readiness"], titles: { ar: "اكتشاف: الروتين اليومي يصنع فرقاً", en: "Discovery: daily routine matters more", de: "Entdeckung: Die tägliche Routine zählt", fr: "Découverte : la routine quotidienne compte", es: "Descubrimiento: la rutina diaria sí importa", tr: "Keşif: günlük rutin gerçekten etkili", pt: "Descoberta: a rotina diária faz diferença" } },
  { slug: "micronutrients-for-conception", section: "planning", type: "research", tags: ["nutrition", "vitamins", "research"], titles: { ar: "بحث مبسط: المغذيات الدقيقة", en: "Research brief: micronutrients for conception", de: "Kurz erklärt: Mikronährstoffe bei Kinderwunsch", fr: "Recherche simple : micronutriments et conception", es: "Investigación simple: micronutrientes y concepción", tr: "Kısa araştırma: gebe kalma için mikro besinler", pt: "Pesquisa simples: micronutrientes para concepção" } },
  { slug: "decision-from-tracking-to-plan", section: "planning", type: "article", tags: ["decision-making", "tracking", "planning"], titles: { ar: "من التتبع إلى الخطة", en: "From tracking to a clear plan", de: "Vom Tracking zum klaren Plan", fr: "Du suivi à un plan clair", es: "Del seguimiento a un plan claro", tr: "Takipten net bir plana", pt: "Do acompanhamento para um plano claro" } },

  // ── PREGNANT (16) ──────────────────────────────────────────────────
  { slug: "pregnancy-week-by-week-guide", section: "pregnant", type: "article", tags: ["weekly-guide", "growth", "planning"], titles: { ar: "دليلكِ أسبوعاً بأسبوع", en: "Your week-by-week pregnancy guide", de: "Schwangerschaftsleitfaden Woche für Woche", fr: "Ton guide grossesse semaine après semaine", es: "Tu guía de embarazo semana a semana", tr: "Hafta hafta gebelik rehberin", pt: "Seu guia de gravidez semana a semana" } },
  { slug: "body-changes-during-pregnancy", section: "pregnant", type: "article", tags: ["body-changes", "comfort", "weekly-guide"], titles: { ar: "فهم تغيرات الجسم أثناء الحمل", en: "Understanding body changes in pregnancy", de: "Körperveränderungen verstehen", fr: "Comprendre les changements du corps", es: "Entender los cambios del cuerpo", tr: "Gebelikte vücut değişimlerini anlamak", pt: "Entender as mudanças do corpo" } },
  { slug: "daily-movement-during-pregnancy", section: "pregnant", type: "article", tags: ["movement", "fitness", "energy"], titles: { ar: "الحركة اليومية للحامل", en: "Daily movement during pregnancy", de: "Tägliche Bewegung in der Schwangerschaft", fr: "Le mouvement au quotidien", es: "Movimiento diario durante el embarazo", tr: "Gebelikte günlük hareket", pt: "Movimento diário durante a gravidez" } },
  { slug: "sleep-during-pregnancy", section: "pregnant", type: "article", tags: ["sleep", "comfort", "routine"], titles: { ar: "النوم أثناء الحمل", en: "Sleeping better during pregnancy", de: "Besser schlafen in der Schwangerschaft", fr: "Mieux dormir pendant la grossesse", es: "Dormir mejor durante el embarazo", tr: "Gebelikte daha iyi uyumak", pt: "Dormir melhor durante a gravidez" } },
  { slug: "smart-pregnancy-nutrition", section: "pregnant", type: "article", tags: ["nutrition", "energy", "routine"], titles: { ar: "التغذية الذكية خلال الحمل", en: "Smart nutrition during pregnancy", de: "Smarte Ernährung in der Schwangerschaft", fr: "Nutrition intelligente pendant la grossesse", es: "Nutrición inteligente durante el embarazo", tr: "Gebelikte akıllı beslenme", pt: "Nutrição inteligente durante a gravidez" } },
  { slug: "weight-gain-with-balance", section: "pregnant", type: "article", tags: ["weight", "nutrition", "tracking"], titles: { ar: "زيادة الوزن بتوازن", en: "Balanced weight gain through pregnancy", de: "Ausgewogene Gewichtszunahme", fr: "Une prise de poids équilibrée", es: "Aumento de peso equilibrado", tr: "Gebelikte dengeli kilo artışı", pt: "Ganho de peso equilibrado" } },
  { slug: "physical-comfort-routines", section: "pregnant", type: "article", tags: ["comfort", "rest", "movement"], titles: { ar: "روتين الراحة الجسدية", en: "Physical comfort routines that help", de: "Routinen für mehr körperliches Wohlbefinden", fr: "Des routines pour plus de confort physique", es: "Rutinas que aportan comodidad física", tr: "Fiziksel rahatlık sağlayan rutinler", pt: "Rotinas que melhoram o conforto físico" } },
  { slug: "birth-preparation-checklist", section: "pregnant", type: "article", tags: ["birth-prep", "planning", "hospital-bag"], titles: { ar: "تجهيز الولادة بثقة", en: "Birth preparation with more confidence", de: "Geburtsvorbereitung mit mehr Sicherheit", fr: "Préparer l'accouchement avec confiance", es: "Prepararte para el parto con confianza", tr: "Doğuma güvenle hazırlanmak", pt: "Preparar o parto com mais confiança" } },
  { slug: "hospital-bag-essentials", section: "pregnant", type: "article", tags: ["hospital-bag", "essentials", "birth-prep"], titles: { ar: "ماذا تضعين في حقيبة المستشفى؟", en: "Hospital bag essentials that matter", de: "Was wirklich in die Kliniktasche gehört", fr: "Les essentiels du sac pour la maternité", es: "Lo esencial para la bolsa del hospital", tr: "Hastane çantasında gerçekten gerekli olanlar", pt: "O essencial para a mala da maternidade" } },
  { slug: "birth-plan-that-feels-real", section: "pregnant", type: "article", tags: ["birth-plan", "planning", "support"], titles: { ar: "خطة ولادة واقعية ومرنة", en: "A birth plan that feels realistic", de: "Ein Geburtsplan, der realistisch bleibt", fr: "Un projet de naissance réaliste et souple", es: "Un plan de parto realista y flexible", tr: "Gerçekçi ve esnek bir doğum planı", pt: "Um plano de parto realista e flexível" } },
  { slug: "baby-movements-explained", section: "pregnant", type: "article", tags: ["baby-movements", "tracking", "awareness"], titles: { ar: "فهم ركلات الطفل", en: "Understanding baby movements", de: "Kindsbewegungen besser verstehen", fr: "Mieux comprendre les mouvements du bébé", es: "Entender los movimientos del bebé", tr: "Bebeğin hareketlerini anlamak", pt: "Entender os movimentos do bebê" } },
  { slug: "contraction-timer-confidence", section: "pregnant", type: "article", tags: ["contractions", "timing", "birth-prep"], titles: { ar: "متى يفيدكِ مؤقت الانقباضات؟", en: "When a contraction timer helps", de: "Wann ein Wehen-Timer wirklich hilft", fr: "Quand le minuteur de contractions aide vraiment", es: "Cuándo ayuda un temporizador de contracciones", tr: "Kasılma sayacı ne zaman işe yarar", pt: "Quando o contador de contrações ajuda" } },
  { slug: "sleep-wellbeing-discovery", section: "pregnant", type: "discovery", tags: ["sleep", "wellbeing", "discovery"], titles: { ar: "اكتشاف: النوم يغيّر يومكِ بالكامل", en: "Discovery: sleep shapes your whole day", de: "Entdeckung: Schlaf verändert den ganzen Tag", fr: "Découverte : le sommeil change toute la journée", es: "Descubrimiento: el sueño cambia todo tu día", tr: "Keşif: uyku tüm gününü etkiler", pt: "Descoberta: o sono muda o seu dia inteiro" } },
  { slug: "light-activity-research", section: "pregnant", type: "research", tags: ["movement", "research", "energy"], titles: { ar: "بحث مبسط: النشاط الخفيف مفيد", en: "Research brief: the value of light activity", de: "Kurz erklärt: Warum leichte Aktivität zählt", fr: "Recherche simple : l'intérêt de l'activité légère", es: "Investigación simple: valor de la actividad ligera", tr: "Kısa araştırma: hafif aktivitenin değeri", pt: "Pesquisa simples: o valor da atividade leve" } },
  { slug: "signs-that-deserve-attention", section: "pregnant", type: "article", tags: ["attention", "awareness", "support"], titles: { ar: "علامات تستحق الانتباه بهدوء", en: "Signs that deserve calm attention", de: "Signale, denen du ruhig Aufmerksamkeit schenken solltest", fr: "Signes à observer avec calme", es: "Señales que merecen atención tranquila", tr: "Sakin şekilde dikkat etmeye değer işaretler", pt: "Sinais que merecem atenção tranquila" } },
  { slug: "partner-support-before-birth", section: "pregnant", type: "article", tags: ["partner", "support", "birth-prep"], titles: { ar: "كيف يقدّم الشريك دعماً فعلياً؟", en: "How a partner can support well", de: "Wie Partner wirklich gut unterstützen können", fr: "Comment le partenaire peut aider concrètement", es: "Cómo puede apoyar mejor la pareja", tr: "Partner nasıl gerçekten iyi destek olur", pt: "Como o parceiro pode apoiar de verdade" } },

  // ── POSTPARTUM (10) ────────────────────────────────────────────────
  { slug: "early-postpartum-recovery", section: "postpartum", type: "article", tags: ["recovery", "rest", "routine"], titles: { ar: "التعافي المبكر بعد الولادة", en: "Early postpartum recovery", de: "Frühe Erholung nach der Geburt", fr: "Le rétablissement au début du post-partum", es: "Recuperación temprana en el posparto", tr: "Doğum sonrası erken toparlanma", pt: "Recuperação inicial no pós-parto" } },
  { slug: "feeding-preparation-and-confidence", section: "postpartum", type: "article", tags: ["feeding", "bonding", "routine"], titles: { ar: "الرضاعة والاستعداد بثقة", en: "Feeding preparation with confidence", de: "Still- und Fütterungsstart mit Sicherheit", fr: "Bien préparer l'alimentation du bébé", es: "Preparar la alimentación con confianza", tr: "Beslenmeye güvenle hazırlanmak", pt: "Preparar a alimentação com confiança" } },
  { slug: "newborn-sleep-rhythm", section: "postpartum", type: "article", tags: ["sleep", "newborn", "routine"], titles: { ar: "بدايات نوم الطفل", en: "Understanding newborn sleep rhythm", de: "Den Schlafrhythmus des Neugeborenen verstehen", fr: "Comprendre le rythme de sommeil du nouveau-né", es: "Entender el ritmo de sueño del recién nacido", tr: "Yenidoğanın uyku ritmini anlamak", pt: "Entender o ritmo de sono do recém-nascido" } },
  { slug: "why-babies-cry", section: "postpartum", type: "article", tags: ["crying", "patterns", "comfort"], titles: { ar: "لماذا يبكي الأطفال؟", en: "Understanding why babies cry", de: "Warum Babys weinen", fr: "Comprendre pourquoi les bébés pleurent", es: "Entender por qué lloran los bebés", tr: "Bebekler neden ağlar", pt: "Entender por que os bebês choram" } },
  { slug: "baby-growth-tracking-basics", section: "postpartum", type: "article", tags: ["growth", "tracking", "feeding"], titles: { ar: "أساسيات تتبع نمو الطفل", en: "Baby growth tracking basics", de: "Grundlagen zum Verfolgen des Babywachstums", fr: "Les bases du suivi de la croissance du bébé", es: "Bases para seguir el crecimiento del bebé", tr: "Bebek gelişimini takip etmenin temelleri", pt: "Noções básicas para acompanhar o crescimento do bebê" } },
  { slug: "first-day-organization", section: "postpartum", type: "article", tags: ["routine", "organization", "support"], titles: { ar: "تنظيم اليوم الأول مع المولود", en: "Organizing the first days with baby", de: "Die ersten Tage mit Baby gut organisieren", fr: "Organiser les premiers jours avec bébé", es: "Organizar los primeros días con el bebé", tr: "Bebekle ilk günleri düzenlemek", pt: "Organizar os primeiros dias com o bebê" } },
  { slug: "balance-after-birth", section: "postpartum", type: "article", tags: ["balance", "rest", "mindset"], titles: { ar: "استعادة التوازن بعد الولادة", en: "Finding balance after birth", de: "Nach der Geburt wieder ins Gleichgewicht finden", fr: "Retrouver son équilibre après la naissance", es: "Recuperar el equilibrio después del parto", tr: "Doğumdan sonra dengeyi yeniden bulmak", pt: "Recuperar o equilíbrio após o parto" } },
  { slug: "fragmented-sleep-research", section: "postpartum", type: "research", tags: ["sleep", "research", "recovery"], titles: { ar: "بحث مبسط: النوم المتقطع", en: "Research brief: fragmented sleep", de: "Kurz erklärt: zerstückelter Schlaf im Alltag", fr: "Recherche simple : le sommeil fractionné", es: "Investigación simple: el sueño fragmentado", tr: "Kısa araştırma: bölünmüş uyku", pt: "Pesquisa simples: sono fragmentado" } },
  { slug: "routine-and-reassurance-discovery", section: "postpartum", type: "discovery", tags: ["routine", "comfort", "discovery"], titles: { ar: "اكتشاف: الروتين يصنع طمأنينة", en: "Discovery: routine builds reassurance", de: "Entdeckung: Routine schafft Sicherheit", fr: "Découverte : la routine apporte de l'apaisement", es: "Descubrimiento: la rutina crea calma", tr: "Keşif: rutin güven hissi oluşturur", pt: "Descoberta: a rotina traz tranquilidade" } },
  { slug: "first-weeks-guide", section: "postpartum", type: "article", tags: ["first-weeks", "support", "feeding"], titles: { ar: "دليل الأسابيع الأولى", en: "A guide for the first weeks", de: "Ein Leitfaden für die ersten Wochen", fr: "Guide des premières semaines", es: "Guía para las primeras semanas", tr: "İlk haftalar için rehber", pt: "Guia para as primeiras semanas" } },
] as const;
