export const ARTICLE_SEED_REGISTRY = [
  { slug: "fertility-window-guide", section: "planning", type: "article", tags: ["fertility", "timing", "cycle-awareness"], titles: { ar: "نافذة الخصوبة بوضوح", en: "Understanding your fertility window", de: "Das Fruchtbarkeitsfenster verstehen", fr: "Comprendre la fenêtre de fertilité", es: "Entender la ventana fértil", tr: "Doğurganlık dönemini anlamak", pt: "Entender a janela fértil" } },
  { slug: "cycle-quality-signals", section: "planning", type: "research", tags: ["cycle-awareness", "patterns", "tracking"], titles: { ar: "إشارات جودة الدورة", en: "Cycle quality signals", de: "Signale der Zyklusqualität", fr: "Signaux de qualité du cycle", es: "Señales de calidad del ciclo", tr: "Döngü kalitesi sinyalleri", pt: "Sinais de qualidade do ciclo" } },
  { slug: "preconception-nutrition-readiness", section: "planning", type: "article", tags: ["nutrition", "readiness", "vitamins"], titles: { ar: "الاستعداد الغذائي قبل الحمل", en: "Nutrition readiness before pregnancy", de: "Ernährungsstart vor der Schwangerschaft", fr: "Préparer la nutrition avant la grossesse", es: "Preparación nutricional antes del embarazo", tr: "Hamilelik öncesi beslenme hazırlığı", pt: "Preparação nutricional antes da gravidez" } },
  { slug: "sleep-and-fertility", section: "planning", type: "research", tags: ["sleep", "fertility", "routine"], titles: { ar: "النوم ودوره في الخصوبة", en: "Sleep and fertility balance", de: "Schlaf und Fruchtbarkeit im Gleichgewicht", fr: "Sommeil et équilibre de fertilité", es: "Sueño y equilibrio de la fertilidad", tr: "Uyku ve doğurganlık dengesi", pt: "Sono e equilíbrio da fertilidade" } },
  { slug: "when-to-use-cycle-tracking", section: "planning", type: "article", tags: ["tracking", "cycle-awareness", "planning"], titles: { ar: "متى يفيد تتبع الدورة فعلاً؟", en: "When cycle tracking helps most", de: "Wann Zyklustracking am meisten hilft", fr: "Quand le suivi du cycle aide le plus", es: "Cuándo ayuda más seguir el ciclo", tr: "Döngü takibi en çok ne zaman fayda sağlar", pt: "Quando o acompanhamento do ciclo ajuda mais" } },
  { slug: "ovulation-practical-guide", section: "planning", type: "article", tags: ["ovulation", "timing", "planning"], titles: { ar: "فهم الإباضة بشكل عملي", en: "A practical guide to ovulation", de: "Ovulation praktisch verstehen", fr: "Comprendre l’ovulation de façon pratique", es: "Entender la ovulación de forma práctica", tr: "Yumurtlamayı pratik şekilde anlamak", pt: "Entender a ovulação de forma prática" } },
  { slug: "emotional-planning-before-pregnancy", section: "planning", type: "article", tags: ["mindset", "planning", "support"], titles: { ar: "الاستعداد النفسي قبل الحمل", en: "Emotional planning before pregnancy", de: "Mentale Vorbereitung vor der Schwangerschaft", fr: "Préparation émotionnelle avant la grossesse", es: "Preparación emocional antes del embarazo", tr: "Hamilelik öncesi duygusal hazırlık", pt: "Planejamento emocional antes da gravidez" } },
  { slug: "common-trying-to-conceive-mistakes", section: "planning", type: "article", tags: ["mistakes", "planning", "fertility"], titles: { ar: "أخطاء شائعة عند محاولة الحمل", en: "Common mistakes while trying to conceive", de: "Häufige Fehler beim Kinderwunsch", fr: "Erreurs fréquentes quand on essaie de concevoir", es: "Errores comunes al intentar concebir", tr: "Hamile kalmaya çalışırken yapılan yaygın hatalar", pt: "Erros comuns ao tentar engravidar" } },
  { slug: "daily-routine-discovery", section: "planning", type: "discovery", tags: ["routine", "sleep", "readiness"], titles: { ar: "اكتشاف: الروتين اليومي يصنع فرقاً", en: "Discovery: daily routine matters more", de: "Entdeckung: Die tägliche Routine zählt", fr: "Découverte : la routine quotidienne compte", es: "Descubrimiento: la rutina diaria sí importa", tr: "Keşif: günlük rutin gerçekten etkili", pt: "Descoberta: a rotina diária faz diferença" } },
  { slug: "micronutrients-for-conception", section: "planning", type: "research", tags: ["nutrition", "vitamins", "research"], titles: { ar: "بحث مبسط: المغذيات الدقيقة", en: "Research brief: micronutrients for conception", de: "Kurz erklärt: Mikronährstoffe bei Kinderwunsch", fr: "Recherche simple : micronutriments et conception", es: "Investigación simple: micronutrientes y concepción", tr: "Kısa araştırma: gebe kalma için mikro besinler", pt: "Pesquisa simples: micronutrientes para concepção" } },
  { slug: "decision-from-tracking-to-plan", section: "planning", type: "article", tags: ["decision-making", "tracking", "planning"], titles: { ar: "من التتبع إلى الخطة", en: "From tracking to a clear plan", de: "Vom Tracking zum klaren Plan", fr: "Du suivi à un plan clair", es: "Del seguimiento a un plan claro", tr: "Takipten net bir plana", pt: "Do acompanhamento para um plano claro" } }
] as const;