name: Cleanup Artifacts

on:
  schedule:
    - cron: "0 0 * * *"                   # يعمل يومياً عند منتصف الليل
  workflow_dispatch:                       # تشغيل يدوي عند الحاجة

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name:*
      name=$(echo "$decoded_row" | jq -r '.name')
      created_at=$(echo "$decoded_row" | jq -r '.created_at')
      echo "Artifact #$counter: $name ($artifact_id) created at $created_at"
      if [ "$counter" -ge "$keep" ]; then
        echo "Deleting artifact: $name with ID: $artifact_id"
        gh api -X DELETE /repos/${{ github.repository }}/actions/artifacts/$artifact_id
      fi
      counter=$((counter + 1))
    done
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
